import type { CheckoutWithGear, GearItem, PackageWithItems } from '@/lib/types';

export const demoGear: GearItem[] = [
  {
    id: '1',
    name: 'Sony FX6 Body',
    category: 'cameras',
    brand: 'Sony',
    model: 'FX6',
    serial_number: 'BB-FX6-001',
    barcode: '111111',
    location: 'Office',
    status: 'Available',
    notes: 'Primary cinema body',
    image_url: null,
    replacement_value: 8500,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    owner_id: 'demo',
  },
  {
    id: '2',
    name: 'Sigma 24-70mm',
    category: 'lenses',
    brand: 'Sigma',
    model: '24-70 f/2.8',
    serial_number: 'BB-LEN-002',
    barcode: '222222',
    location: 'Studio',
    status: 'Checked Out',
    notes: null,
    image_url: null,
    replacement_value: 1700,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    owner_id: 'demo',
  },
  {
    id: '3',
    name: 'Aputure 600D Pro',
    category: 'lighting',
    brand: 'Aputure',
    model: '600D Pro',
    serial_number: 'BB-LGT-003',
    barcode: '333333',
    location: 'Studio',
    status: 'Maintenance',
    notes: 'Inspect ballast cable',
    image_url: null,
    replacement_value: 2500,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    owner_id: 'demo',
  },
];

export const demoPackages: PackageWithItems[] = [
  {
    id: 'pkg1',
    name: 'Interview Core Kit',
    project_name: 'Client Testimonial',
    prep_date: new Date().toISOString().slice(0, 10),
    notes: 'Two-camera sit-down interview package',
    status: 'Prepped',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    owner_id: 'demo',
    package_items: [
      { id: 'pi1', package_id: 'pkg1', gear_item_id: '1', created_at: new Date().toISOString(), gear_items: demoGear[0] },
      { id: 'pi2', package_id: 'pkg1', gear_item_id: '2', created_at: new Date().toISOString(), gear_items: demoGear[1] },
    ],
  },
];

export const demoCheckouts: CheckoutWithGear[] = [
  {
    id: 'co1',
    gear_item_id: '2',
    package_id: 'pkg1',
    assignee_name: 'Tristan',
    project_name: 'Client Testimonial',
    due_back: new Date().toISOString().slice(0, 10),
    checked_out_at: new Date().toISOString(),
    returned_at: null,
    notes: 'On-location interview',
    owner_id: 'demo',
    gear_items: demoGear[1],
  },
];
